// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKiqUgodXoMtzv8idWyKhNQcoeRt67qlc',
    appId: '1:635095137113:web:f66d98f3ab710e1b142a48',
    messagingSenderId: '635095137113',
    projectId: 'windbyauth',
    authDomain: 'windbyauth.firebaseapp.com',
    storageBucket: 'windbyauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiU24jKOlnhDOqaSvZ3es-WJMQKhhhsrs',
    appId: '1:635095137113:android:848edbae8620ab93142a48',
    messagingSenderId: '635095137113',
    projectId: 'windbyauth',
    storageBucket: 'windbyauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAha4lur7Zux1lozYjNRDrayHMzo0v5VoY',
    appId: '1:635095137113:ios:c3538a25e414fd2a142a48',
    messagingSenderId: '635095137113',
    projectId: 'windbyauth',
    storageBucket: 'windbyauth.appspot.com',
    iosBundleId: 'com.example.windby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAha4lur7Zux1lozYjNRDrayHMzo0v5VoY',
    appId: '1:635095137113:ios:3181e4afc93a5fd0142a48',
    messagingSenderId: '635095137113',
    projectId: 'windbyauth',
    storageBucket: 'windbyauth.appspot.com',
    iosBundleId: 'com.example.windby.RunnerTests',
  );
}
